language: java
jdk: openjdk8

stages:
  - name: build
  - name: test
  - name: snapshot
    if: branch = master AND type = push AND fork = false
  - name: release
    if: tag IS present

services:
  - docker

cache:
  directories:
  - $HOME/.m2

before_install:
  - git clone --recurse-submodules git://github.com/openmicroscopy/omero-test-infra .omero
  - export DOCKER_ARGS="-v $HOME/.m2:/root/.m2 -v $(pwd)/target:/src/target"
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: build
      script:
        - mvn compile
    - stage: test
      script:
        - set -e
        - .omero/lib-docker
    - stage: snapshot
      script:
        - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
        - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
        - mvn versions:set -DnewVersion=$project_version-SNAPSHOT
        - mvn package -DskipTests
        - mvn deploy -DskipTests
    - stage: release
      script:
        - mvn package -DskipTests
        - mvn deploy -DskipTests

